### ISSUE TITLE
Harmful Score

### ISSUE THREAD

**Issue by imhgchoi** [git-disl/Vaccine#1]
Hello! I really like your work - very impressive!!

Just had a quick question regarding the harmful score computation.
Is the eval_sentiment.py under Vaccine/poison/evaluation/ the code that computes the harmful score?

Thank you very much!

**Comment by huangtiansheng** [comment]
Yes. That's the right place.We call a moderation model from Beavertails to evaluate the harmful score. Please check out their model https://huggingface.co/PKU-Alignment/beaver-dam-7b.

**Comment by imhgchoi** [comment]
Thank you very much - appreciate it :)
