### ISSUE TITLE
Consider adding license

### ISSUE THREAD

**Issue by rank-and-file** [git-disl/Vaccine#2]
Hey, thanks for this important and interesting work :+1:
I would like to extend your code, but it would be super helpful if it had a license.

You might not be aware of this, but without a license, no one can use your code legally.

[This](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license) is a helpful resource regarding this.

In my experience, most repositories choose a license such as Apache 2.0 or MIT. (E.g. DPO https://github.com/eric-mitchell/direct-preference-optimization uses Apache-2.0)

The license is specified in a file called "`LICENSE`" in the root directory of the project. 
E.g. https://github.com/eric-mitchell/direct-preference-optimization/blob/main/LICENSE

**Comment by huangtiansheng** [comment]
Sure. Thanks for the reminding! We have updated the license. Feel free to extend our code!
